//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLuanAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuanVan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LuanVan()
        {
            this.NhiemVus = new HashSet<NhiemVu>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public string YeuCau { get; set; }
        public Nullable<int> SoLuongSinhVien { get; set; }
        public string TheLoai { get; set; }
        public string CongNghe { get; set; }
        public Nullable<int> GiangVienID { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhiemVu> NhiemVus { get; set; }
    }
}
