//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLuanAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhiemVu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhiemVu()
        {
            this.CauHoiNhiemVus = new HashSet<CauHoiNhiemVu>();
            this.NhiemVuSinhViens = new HashSet<NhiemVuSinhVien>();
        }
    
        public int ID { get; set; }
        public string Ten { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> TienDo { get; set; }
        public Nullable<int> LuanVanID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHoiNhiemVu> CauHoiNhiemVus { get; set; }
        public virtual LuanVan LuanVan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhiemVuSinhVien> NhiemVuSinhViens { get; set; }
    }
}
