//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLuanAn
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhiemVuSinhVien
    {
        public int ID { get; set; }
        public Nullable<int> TiLePhanCham { get; set; }
        public Nullable<int> SVID { get; set; }
        public Nullable<int> NhiemVuID { get; set; }
    
        public virtual NhiemVu NhiemVu { get; set; }
        public virtual SinhVien SinhVien { get; set; }
    }
}
